/**
 * Photography manifest for /disciplines/[slug] pages.
 *
 * Each entry holds the optimised WebPs that live under
 * public/images/disciplines/{slug}/ — generated by
 * `npm run images:intern`. The disciplines/[slug] renderer reads from
 * this map and shows a PhotoSlideshow under the hero for disciplines
 * with photography available. Disciplines not listed here render
 * without a photo strip until images land.
 */

export interface DisciplineImages {
  /** Full path to the hero shot under /public. */
  hero: string;
  /** Alt text for the hero — should describe the trade + brand context. */
  heroAlt: string;
  /** Gallery image paths in display order. */
  gallery: string[];
}

const ROOT = "/images/disciplines";

export const DISCIPLINE_IMAGES: Record<string, DisciplineImages> = {
  "waterproofing": {
    hero: `${ROOT}/waterproofing/hero.webp`,
    heroAlt: "Sixty Newton — liquid-membrane waterproofing, MAPEI applicator",
    gallery: [],
  },

  "bitumen-waterproofing": {
    hero: `${ROOT}/bitumen-waterproofing/hero.webp`,
    heroAlt: "Sixty Newton — APP bitumen torch-applied roof membrane",
    gallery: [
      `${ROOT}/bitumen-waterproofing/gallery-1.webp`,
      `${ROOT}/bitumen-waterproofing/gallery-2.webp`,
      `${ROOT}/bitumen-waterproofing/gallery-3.webp`,
      `${ROOT}/bitumen-waterproofing/gallery-4.webp`,
    ],
  },

  "microtopping": {
    hero: `${ROOT}/microtopping/hero.webp`,
    heroAlt: "Sixty Newton — microtopping / microcement seamless finish",
    gallery: [`${ROOT}/microtopping/gallery-1.webp`],
  },

  "epoxy-flooring": {
    hero: `${ROOT}/epoxy-flooring/hero.webp`,
    heroAlt: "Sixty Newton — epoxy flooring application, brand-certified applicator",
    gallery: [`${ROOT}/epoxy-flooring/gallery-1.webp`],
  },

  "large-format-tiling": {
    hero: `${ROOT}/large-format-tiling/hero.webp`,
    heroAlt: "Sixty Newton — large-format porcelain tiling, Mapei / Laticrete spec",
    gallery: [
      `${ROOT}/large-format-tiling/gallery-1.webp`,
      `${ROOT}/large-format-tiling/gallery-2.webp`,
    ],
  },

  "marble-installation": {
    hero: `${ROOT}/marble-installation/hero.webp`,
    heroAlt: "Sixty Newton — marble installation, Laticrete-spec setting beds",
    gallery: [],
  },

  "self-levelling": {
    hero: `${ROOT}/self-levelling/hero.webp`,
    heroAlt: "Sixty Newton — self-levelling screed application on a live site",
    gallery: [
      `${ROOT}/self-levelling/gallery-1.webp`,
      `${ROOT}/self-levelling/gallery-2.webp`,
      `${ROOT}/self-levelling/gallery-3.webp`,
      `${ROOT}/self-levelling/gallery-4.webp`,
      `${ROOT}/self-levelling/gallery-5.webp`,
    ],
  },

  "vinyl-flooring": {
    hero: `${ROOT}/vinyl-flooring/hero.webp`,
    heroAlt: "Sixty Newton — LVT vinyl flooring installation, MAPEI Ultrabond spec",
    gallery: [],
  },

  "polishing": {
    hero: `${ROOT}/polishing/hero.webp`,
    heroAlt: "Sixty Newton — marble & floor polishing, diamond-pad grit progression",
    gallery: [],
  },

  "specialised-coatings-and-sealants": {
    hero: `${ROOT}/specialised-coatings-and-sealants/hero.webp`,
    heroAlt: "Sixty Newton — specialised PU coatings and joint sealants",
    gallery: [],
  },

  "painting": {
    hero: `${ROOT}/painting/hero.webp`,
    heroAlt: "Sixty Newton — interior & exterior painting, AkzoNobel Dulux applicator",
    gallery: [],
  },
};

export function getDisciplineImages(slug: string): DisciplineImages | undefined {
  return DISCIPLINE_IMAGES[slug];
}
